# Generated by Django 4.1.5 on 2023-01-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('author', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='photos/')),
                ('date_published', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=300)),
                ('article', models.TextField()),
            ],
        ),
    ]
